export const WEATHER_CODES: Record<number, string> = {
	0: "Klart",
	1: "Mest klart",
	2: "Delvis molnigt",
	3: "Mulet",
	45: "Dimma",
	48: "Rimfrost",
	51: "Lätt duggregn",
	53: "Duggregn",
	55: "Kraftigt duggregn",
	61: "Lätt regn",
	63: "Regn",
	65: "Kraftigt regn",
	71: "Lätt snö",
	73: "Snö",
	75: "Kraftig snö",
	80: "Regnskurar",
	81: "Kraftiga regnskurar",
	82: "Kraftiga skurar",
	95: "Åska",
	96: "Åska med hagel",
	99: "Åska med hagel",
};
